branch-defaults:
  develop:
    environment: nestjs-devops
environment-defaults:
  nestjs-devops:
    branch: null
    repository: null
global:
  application_name: nestjs-devops
  default_ec2_keyname: nestjs-devops
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
